# Generated by Django 4.1 on 2022-10-18 06:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(model_name="post", name="images",),
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(
                null=True, validators=[django.core.validators.MinLengthValidator(10)]
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.author",
            ),
        ),
        migrations.AlterField(
            model_name="post", name="date", field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
        migrations.AddField(
            model_name="post", name="tag", field=models.ManyToManyField(to="blog.tag"),
        ),
    ]
