# Generated by Django 4.1 on 2022-11-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_tag_remove_post_images_author_email_post_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="image",),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ImageField(null=True, upload_to="posts"),
        ),
    ]
